/**
 * Cloudflare Worker entry point — auto-generated by vinext deploy.
 * Edit freely or delete to regenerate on next deploy.
 *
 * For apps without image optimization, you can use vinext/server/app-router-entry
 * directly in wrangler.jsonc: "main": "vinext/server/app-router-entry"
 */
import { handleImageOptimization, DEFAULT_DEVICE_SIZES, DEFAULT_IMAGE_SIZES } from "vinext/server/image-optimization";
import handler from "vinext/server/app-router-entry";

interface Env {
  ASSETS: Fetcher;
  DB?: D1Database;
  IMAGES: {
    input(stream: ReadableStream): {
      transform(options: Record<string, unknown>): {
        output(options: { format: string; quality: number }): Promise<{ response(): Response }>;
      };
    };
  };
}

export default {
  async fetch(request: Request, env: Env): Promise<Response> {
    const url = new URL(request.url);

    // Image optimization via Cloudflare Images binding.
    // The parseImageParams validation inside handleImageOptimization
    // normalizes backslashes and validates the origin hasn't changed.
    if (url.pathname === "/_vinext/image") {
      const allowedWidths = [...DEFAULT_DEVICE_SIZES, ...DEFAULT_IMAGE_SIZES];
      return handleImageOptimization(request, {
        fetchAsset: (path) => env.ASSETS.fetch(new Request(new URL(path, request.url))),
        transformImage: async (body, { width, format, quality }) => {
          const result = await env.IMAGES.input(body).transform(width > 0 ? { width } : {}).output({ format, quality });
          return result.response();
        },
      }, allowedWidths);
    }

    // Markdown for Agents: serve /llms.txt as the markdown representation
    // of the homepage when an agent asks for text/markdown.
    if (
      (url.pathname === "/" || url.pathname === "") &&
      (request.headers.get("accept") ?? "").includes("text/markdown")
    ) {
      const md = await env.ASSETS.fetch(
        new Request(new URL("/llms.txt", request.url))
      );
      if (md.ok) {
        const text = await md.text();
        const tokens = text.split(/\s+/).filter(Boolean).length;
        return new Response(text, {
          headers: {
            "Content-Type": "text/markdown; charset=utf-8",
            "x-markdown-tokens": String(tokens),
            "Cache-Control": "public, max-age=3600",
          },
        });
      }
    }

    // Delegate everything else to vinext
    const res = await handler.fetch(request);

    // Add agent-discovery Link headers on the homepage (RFC 8288)
    if (url.pathname === "/" || url.pathname === "") {
      const headers = new Headers(res.headers);
      headers.append(
        "Link",
        [
          '</sitemap.xml>; rel="sitemap"; type="application/xml"',
          '</llms.txt>; rel="alternate"; type="text/plain"; title="LLM-friendly summary"',
          '<https://dmitry.ie>; rel="author"; title="Dmitry Alexeenko"',
        ].join(", ")
      );
      return new Response(res.body, {
        status: res.status,
        statusText: res.statusText,
        headers,
      });
    }

    return res;
  },
};
